[project]
name = "deepnet-zero-hero"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "xhc" }
]
requires-python = ">=3.11"
dependencies = [
    "graphviz>=0.21",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "numpy>=2.4.6",
    "scikit-learn>=1.9.1",
]

[project.scripts]
deepnet-zero-hero = "deepnet_zero_hero:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "deepnet_zero_hero"
namespace = true
